name: Update Products Cronjob

on:
  schedule:
    # 09:05 a.m. CDMX  -> 15:05 UTC
    - cron: "5 15 * * *"
    # 04:05 p.m. CDMX  -> 22:05 UTC
    - cron: "5 22 * * *"
  workflow_dispatch:

jobs:
  update_products:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        store: [HHGLOBAL, GNP, PSP]

    env:
      GRAPHQL_URL: ${{ secrets[ format('GRAPHQL_URL_{0}', matrix.store) ] }}
      SHOPIFY_TOKEN: ${{ secrets[ format('SHOPIFY_TOKEN_{0}', matrix.store) ] }}
      INNOVA_USER: ${{ secrets.INNOVA_USER }}
      INNOVA_PASSWORD: ${{ secrets.INNOVA_PASSWORD }}
      INNOVA_AUTH_TOKEN: ${{ secrets.INNOVA_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: "18" }
      - run: npm install
      - name: Run update for ${{ matrix.store }}
        run: node index.js
